### ISSUE TITLE
Реализовать возможность простого запуска по Mac OS x

### ISSUE THREAD

**Issue by Timopheym** [trousev/cleer#46]
Скачал последнюю версию. 
Если программа не находит файл БД, не создает его автоматом.
Может надо создать пустую БД.. но как-то это все не "юзабилити"..

``` bash

$ java -jar ./cleer-desktop-0.1-rev312.jar 
Exception in thread "main" java.sql.SQLException: path to '/Users/T/.config/cleer/database.sqlite': '/Users/T/.config/cleer' does not exist
    at org.sqlite.Conn.open(Conn.java:103)
    at org.sqlite.Conn.<init>(Conn.java:57)
    at org.sqlite.JDBC.createConnection(JDBC.java:77)
    at org.sqlite.JDBC.connect(JDBC.java:64)
    at java.sql.DriverManager.getConnection(DriverManager.java:571)
    at java.sql.DriverManager.getConnection(DriverManager.java:233)
    at pro.trousev.cleer.sys.DatabaseSqlite.<init>(Unknown Source)
    at pro.trousev.cleer.desktop.ConsoleClient.main(Unknown Source)
T at MacBook-Pro-2.local  ~/Downloads
$ touch database.sqlite
T at MacBook-Pro-2.local  ~/Downloads
$ java -jar ./cleer-desktop-0.1-rev312.jar 
    at org.sqlite.Conn.<init>(Conn.java:57)
    at org.sqlite.JDBC.createConnection(JDBC.java:77)
    at org.sqlite.JDBC.connect(JDBC.java:64)
    at java.sql.DriverManager.getConnection(DriverManager.java:571)
    at java.sql.DriverManager.getConnection(DriverManager.java:233)
    at pro.trousev.cleer.sys.DatabaseSqlite.<init>(Unknown Source)
    at pro.trousev.cleer.desktop.ConsoleClient.main(Unknown Source)

```

``` bash
$ uname -a
Darwin MacBook-Pro-2.local 12.5.0 Darwin Kernel Version 12.5.0: Sun Sep 29 13:33:47 PDT 2013; root:xnu-2050.48.12~1/RELEASE_X86_64 x86_64
$ java -version
java version "1.7.0_40"
Java(TM) SE Runtime Environment (build 1.7.0_40-b43)
Java HotSpot(TM) 64-Bit Server VM (build 24.0-b56, mixed mode)

```

**Comment by trousev** [comment]
Похоже, не создается ~/.config , если его не было.

**Comment by volodkuzn** [comment]
В старых версиях всё было хорошо. Раньше я нормально запускал. Версия, собранная 10 мая прошлого года работает.

Володя.

10.01.2014, в 21:40, Alexander Trousevich написал(а):

**Comment by trousev** [comment]
Даже хуже. При существующей ~/.config не создается ~/.config/cleer

HTR:
1. Удалить папку ~/.config/cleer
2. Запустить плеер
3. Увидеть исключение.

поправлю, чо.

**Comment by trousev** [comment]
Скорее всего поправлено в  5612935
