### ISSUE TITLE
Невозможно создать id3v1 рейтинг

### ISSUE THREAD

**Issue by trousev** [trousev/cleer#48]
При попытки прорейтить запись с id3v1 тегом приезжает

java.lang.NullPointerException
        at org.jaudiotagger.tag.id3.ID3v1Tag.createField(ID3v1Tag.java:682)
        at org.jaudiotagger.tag.id3.ID3v1Tag.setField(ID3v1Tag.java:628)
        at pro.trousev.cleer.sys.AudioFileHeader.setTags(Unknown Source)
        at pro.trousev.cleer.sys.MediaItem$1.writeTag(Unknown Source)
        at pro.trousev.cleer.sys.StandardItem.setTagValue(Unknown Source)
        at pro.trousev.cleer.sys.StandardTag.setValue(Unknown Source)
        at pro.trousev.cleer.commands.RatingManagement$Rate.main(Unknown Source)
        at pro.trousev.cleer.commands.CoreConsole.invoke(Unknown Source)
        at pro.trousev.cleer.desktop.ConsoleClient.main(Unknown Source)

А надо создавать id3v2 втихую, копируя туда id3v1 теги и рейтить.

**Comment by trousev** [comment]
This issue was moved to trousev/cleercopy#1
